---
kind: ConfigMap
apiVersion: v1
metadata:
  name: schema-config
  labels:
    app: loki
data:
  loki.yaml: |
    schema_config:
      configs:
      - from: "2020-02-15"
        index:
          period: 168h
          prefix: index_
        object_store: filesystem
        schema: v11
        store: boltdb
    storage_config:
      boltdb:
        directory: /data/loki/index
      filesystem:
        directory: /data/loki/chunks
