apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: default-logging
spec:
  fluentd: 
    scaling:
      replicas: 3
    resources:
      limits: 
        cpu: "2"
        memory: 1024M
      requests:
        cpu: "1"
        memory: 500M
  fluentbit: {}
  controlNamespace: monitoring