apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  labels:
    scope: system
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://hub.helm.sh'
    targetRevision: 5.0.21
    chart: minio
    helm:
      parameters:
        - name: accessKey
          value: 'azurestorageaccountname'
        - name: accessKey
          value: 'azurestorageaccountname'
  project: monitoring
  syncPolicy:
    automated: {}
