apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  labels:
    scope: system
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://kubernetes-charts.storage.googleapis.com/'
    targetRevision: 5.0.21
    chart: minio
    helm:
      parameters:
        - name: accessKey
          value: "AZURE_REQUESTOR_ACCOUNT_ACCESS_KEY"
        - name: secretKey
          value: "AZURE_REQUESTOR_ACCOUNT_SECRETE_KEY"
  project: monitoring
  syncPolicy:
    automated: {}
