apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    scope: system
spec:
  dependencies:
  - name: minio
    version: 5.0.21
    repository: https://kubernetes-charts.storage.googleapis.com
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: base/monitoring/minio
    repoURL: https://github.com/muqtadir/loki-microservice.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
