apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    scope: system
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://kubernetes-charts.storage.googleapis.com/'
    targetRevision: 5.0.21
    chart: minio
    helm:
      releaseName: minio
      valueFiles:
        - values.yml
        - values-production.yml
        - values-performance.yml
  project: monitoring
  syncPolicy:
    automated: {}
