apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-minio
  namespace: argocd
  labels:
    scope: system
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://kubernetes-charts.storage.googleapis.com/'
    targetRevision: 5.0.21
    helm:
      parameters:
        - name: accessKey
          value: $azureAccessKey
        - name: secretKey
          value: $azureSecretKey
        - name: azuregateway.enabled
          value: 'true'
        - name: azuregateway.replicas
          value: '4'
        - name: s3gateway.enabled
          value: 'false'
        - name: service.annotations
          value: |
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    chart: minio
  project: monitoring
syncPolicy:
  automated: {}

