---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingester
  labels:
    app: loki
  annotations:
    prometheus.io/port: http-metrics
    prometheus.io/scrape: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ingester

  # Ingesters are not ready for at least 1 min
  # after creation.  This has to be in sync with
  # the ring timeout value, as this will stop a
  # stampede of new ingesters if we should loose
  # some.
  minReadySeconds: 60

  # Having maxSurge 0 and maxUnavailable 1 means
  # the deployment will update one ingester at a time
  # as it will have to stop one (making one unavailable)
  # before it can start one (surge of zero)
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  template:
    metadata:
      labels:
        name: ingester
        app: loki
    spec:
      # Give ingesters 40 minutes grace to flush chunks and exit cleanly.
      # Service is available during this time, as long as we don't stop
      # too many ingesters at once.
      terminationGracePeriodSeconds: 2400

      serviceAccountName: loki
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001

      containers:
      - name: ingester
        image: grafana/loki:1.4.0
        imagePullPolicy: Always
        args:
        - -target=ingester
        - -ingester.join-after=30s
        - -server.http-listen-port=8080
        - -consul.hostname=loki-consul:8500
        - -s3.url=s3://abc:123@s3:4569
        - -config.file=/etc/loki/loki.yaml
        ports:
        - name: http-metrics
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 45
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 45
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
          - name: config-volume
            mountPath: /etc/loki
          - name: storage
            mountPath: "/data"
            subPath: "loki"
      volumes:
        - name: storage
          emptyDir: {}
        - name: config-volume
          configMap:
            name: schema-config
