apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  labels:
    scope: system
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  source:
    repoURL: 'https://github.com/muqtadir/loki-microservice.git'
    path: base/monitoring/loki
    targetRevision: HEAD
  project: monitoring
  syncPolicy:
    automated: {}
