---
apiVersion: v1
kind: Service
metadata:
  name: query-frontend
  labels:
    app: loki
spec:
  # clusterIP: None gives a "headless" service so DNS returns all endpoints.
  type: ClusterIP
  ports:
    - port: 9095
      name: grcp
    - port: 3100
      name: http
      targetPort: 3100
  selector:
    name: query-frontend
    sessionAffinity: None
