---
apiVersion: v1
kind: Service
metadata:
  name: query-frontend
  labels:
    name: query-frontend
    app: loki
spec:
  # clusterIP: None gives a "headless" service so DNS returns all endpoints.
  clusterIP: None
  ports:
    - port: 9095
      name: grcp
    - port: 3100
      name: query-frontend-http
      protocol: TCP
      targetPort: 3100
  selector:
    name: query-frontend
