---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-frontend
  labels:
    app: loki
  annotations:
    prometheus.io/port: http
    prometheus.io/scrape: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      name: query-frontend
  template:
    metadata:
      labels:
        name: query-frontend
        app: loki
    spec:
      serviceAccountName: loki
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      containers:
      - name: query-frontend
        image: grafana/loki:1.4.0
        imagePullPolicy: Always
        args:
        - -config.file=/etc/loki/config.yaml
        - -target=query-frontend
        - -log.level=debug
        volumeMounts:
        - name: query-frontend
          mountPath: /etc/loki
        ports:
        - containerPort: 9095
          name: grpc
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 15
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 15
        resources:
          limits:
            memory: 1200Mi
          requests:
            cpu: "2"
            memory: 600Mi
        securityContext:
          readOnlyRootFilesystem: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      volumes:
        - name: query-frontend
          configMap:
            defaultMode: 420
            name: query-frontend
