apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- loki-config.yml
configMapGenerator:
- name: loki-parameters
  env: params.env
vars:
- name: replicationfactor
  objref:
    kind: ConfigMap
    name: loki
    apiVersion: v1
  fieldref:
    fieldpath: ingester.lifecycler.ring
