---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  labels:
    scope: system
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: monitoring
  source:
    path: local-setup
    repoURL: https://github.com/muqtadir/loki-microservice.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
