---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: table-manager
  labels:
    app: loki
  annotations:
    prometheus.io/port: http-metrics
    prometheus.io/scrape: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      name: table-manager
  template:
    metadata:
      labels:
        name: table-manager
        app: loki
    spec:
      serviceAccountName: loki
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      containers:
      - name: table-manager
        image: grafana/loki:1.4.0
        imagePullPolicy: Always
        args:
        - -target=table-manager
        - -server.http-listen-port=8080
        - -config.file=/etc/loki/loki.yaml
        volumeMounts:
          - name: config-volume
            mountPath: /etc/loki
          - name: storage
            mountPath: "/data"
            subPath: "loki"
        ports:
          - name: http-metrics
            containerPort: 8080
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 45

        readinessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 45
        securityContext:
          readOnlyRootFilesystem: true

      terminationGracePeriodSeconds: 4800

      volumes:
        - name: storage
          emptyDir: {}
        - name: config-volume
          configMap:
            name: schema-config
