apiVersion: v1
data:
  config.yaml: |
    ingester:        
        lifecycler:
            ring:
                replication_factor: 1
kind: ConfigMap
metadata:
  name: loki
  annotations:
    kustomize.config.k8s.io/behavior: "replace"
